import { SocketProvider } from '@/providers/socket-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

declare module 'react' {
  interface CSSProperties {
    [key: `--${string}`]: string;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
      <SocketProvider>
        {children}
      </SocketProvider>
      </body>
    </html>
  )
}
